spring:
  cloud:
    stream:
#      rocketmq:
#        bindings:
#          huxintestOutput:
#            producer:
#              group: huxintestOutput-DF
      bindings: #注意：rocketmq中不允许相同的consumerGroup消费不同的topic，会造成数据丢失
        userStatusChangeConsumer:
          destination: idaas_user_user_status_change_test
          group: idaas_user_user_status_change_test
          binder: kafka1
#        huxintestOutput:
#          destination: huxin_test
#          binder: rocketmq1

#      binders:
#        kafka1:
#          type: kafka
#          environment:
#            spring:
#              cloud:
#                stream:
#                  kafka:
#                    binder:
#                      brokers: 116.205.180.164:9092
#                      auto-create-topics: true
#        rocketmq1:
#          type: rocketmq
#          environment:
#            spring:
#              cloud:
#                stream:
#                  rocketmq:
#                    binder:
#                      name-server: 10.10.2.99:9876


jarvis:
  scs:
    binders:
      kafka1:
        type: kafka
        environment:
          spring:
            cloud:
              stream:
                kafka:
                  binder:
                    brokers: 10.10.2.52:9092
                    auto-create-topics: true
      rocketmq1:
        type: rocketmq
        environment:
          spring:
            cloud:
              stream:
                rocketmq:
                  binder:
                    name-server: 10.10.2.99:9876
                    auto-create-topics: true

    bindings:
      huxintestInput:
        destination: huxin_test
        group: huxin_test
        binder: rocketmq1
        type: input
        startOffset: earliest
        consumer:
          concurrency: 5
      userStatusChangeProducer:
        destination: idaas_user_user_status_change_test
        binder: rocketmq1
        type: output
        producer:
          #需要在message $ header中增加partitionKey的k-v对
          partitionKeyExpression: headers['partitionKey']
      userStatusChangeInput:
        destination: idaas_user_user_status_change_test
        group: idaas_user_user_status_change_test
        binder: kafka1
        type: input
        messageModel: BROADCASTING
#      userStatusChangeConsumer:
#        destination: idaas_user_user_status_change_test
#        group: idaas_user_user_status_change_test
#        binder: kafka1
#        type: input
      huxintestOutput:
         destination: huxin_test
         type: output
         binder: rocketmq1











